### ISSUE TITLE
404 error in codealongs

### ISSUE THREAD

**Issue by ryuichi7** [learn-co-curriculum/sql-insert-select-update-code-along#11]
The first three codealongs in this track, SQL "getting started" have had dead links to github. Maybe you updated the names recently? Anyway, I'd love to be able to follow along in the exercises!

Thanks.

**Comment by AnnJohn** [comment]
hi @ryuichi7 thanks for raising this issue. it looks like a problem with our deployer so we'll fix this soon.

**Comment by AnnJohn** [comment]
hi @ryuichi7 those lessons have been updated. thanks again!
