### ISSUE TITLE
@avidor Lab instructions are unclear for connecting Sqlite to pets_database

### ISSUE THREAD

**Issue by mdjurdj1** [learn-co-curriculum/sql-insert-select-update-code-along#18]
One student showed confusion when trying to access their pets_database after exiting the Sqlite console, since the lab did not specify that Sqlite needed to "connect' or be made aware of the pets_database in order to modify pets_database. 

Student was able to resume working on the lab after running `sqlite3 pets_database.db` from BASH again.

**Comment by gj** [comment]
Hi @mdjurdj1 !

Not super concerned about this since the first instruction tells students to run that command, but maybe I'm missing something. What's your suggestion?

Thanks for contributing! 🙂

**Comment by justinddaniel** [comment]
Perhaps make it clearer that for the first part: Setting up our Database, students should enter the command into terminal and NOT be in sqlite yet. I just had another confused student get stuck on this.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
