### ISSUE TITLE
Escaping the single quote in SQL

### ISSUE THREAD

**Issue by joshuabamboo** [learn-co-curriculum/sql-insert-select-update-code-along#19]
The code along has students enter a value with an escaped single quote: `'Lil\' Bub'`. Everything in the reading shows the string being escaped with a backslash, but the actual SQL command to escape is to put two single quotes, eg `'Lil'' Bub'`. Might be worth including a hint, resource, or note.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
