### ISSUE TITLE
Lil\'Bub vs Lil'Bub

### ISSUE THREAD

**Issue by azharshahstl** [learn-co-curriculum/sql-insert-select-update-code-along#20]
The name of the cat is spelled 2 different ways as mentioned above.  Lil\'Bub is added to the table, but Lil'Bub is to be deleted.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
