### ISSUE TITLE
Ide not working properly

### ISSUE THREAD

**Issue by katreesedarcene** [learn-co-curriculum/sql-insert-select-update-code-along#21]
Not able to see pets_database. Getting an error when adding files to01_insert_cats_into_cats_table.sq ..There should be an explanation that Control d is a way to exit sql 

I am not able to finish the lab as is.

**Comment by drakeltheryuujin** [comment]
Hi there! This request sounds like a problem with the Learn platform.

Our product team can help you with this. You can reach them at support@learn.co.

[Raising issues on GitHub][raise], like you've done here should happen when
there are problems with the curriculum itself (doesn't work, throws a Ruby
error, etc.)

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can to clarify our error,
and we will try to find a fix.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
