### ISSUE TITLE
unable to create table in IDE sandbox in this and subsequent labs

### ISSUE THREAD

**Issue by JohnathanCh** [learn-co-curriculum/sql-insert-select-update-code-along#22]
A student and I worked through the lab together. He was able to build the database, but when he created the file `01_create_cats_table.sql`:
```
CREATE TABLE cats (
	id INTEGER PRIMARY KEY,
	name TEXT,
	age INTEGER,
	breed TEXT
);
```
and tried to run it using:
`sqlite3 pets_database.db < 01_create_cats_table.sql`

It wouldn't work.

**Comment by drakeltheryuujin** [comment]
Hi there! This request sounds like a problem with the Learn platform.

Our product team can help you with this. You can reach them at support@learn.co.

[Raising issues on GitHub][raise], like you've done here should happen when
there are problems with the curriculum itself (doesn't work, throws a Ruby
error, etc.)

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can to clarify our error,
and we will try to find a fix.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
